In [1]:
import numpy as np

from allen_v1dd.client import OPhysClient
from allen_v1dd.stimulus_analysis import NaturalImages, NaturalMovie

%load_ext autoreload
%autoreload 2

In [2]:
client = OPhysClient("/Users/chase/Desktop/test_v1dd_data/")

In [3]:
session = client.load_ophys_session("M438833_13")

In [4]:
plane = session.get_planes()[0]

In [5]:
nm = NaturalMovie(session, plane, compute_chisq=False)

In [6]:
nm.frame_indices

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
nm.stim_meta

{'num_samples': 27000}

In [8]:
for frame_i in nm.frame_indices:
    stim_idx = nm.get_stim_idx(frame_i)
    frame_data = nm.sweep_responses[stim_idx, :].T # shape (n_rois, n_frame_repeats) note n_frame_repeats not necessarily = n_repeats
    print(frame_data.shape)

    if frame_i > 10:
        break


(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)


In [9]:
nm.sweep_responses.shape

(27000, 1494)

In [10]:
nm.trial_responses

<xarray.DataArray 'trial_responses' (roi: 1494, frame: 900, repeat: 30)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00524653],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00524653],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00524653],
        ...,
        [0.        , 0.        , 0.0078408 , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.0078408 , ..., 0.        ,
         0.00524653, 0.        ],
        [0.        , 0.        , 0.0078408 , ..., 0.        ,
         0.00524653, 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.00901487, ..., 0.        ,
         0.00497372, 0.00805673],
        [0.        , 0.        , 0.00901487, ..., 0.        ,
         0.00497372, 0.00805673],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00805673],
        ...,
        [0.        , 0.00901487, 0.        , ..., 0.00497372,
         0.00805673, 0.        ],
        [0.        , 0.00901487, 0.        , ..., 0.00497372,
         0.00805673, 0.        ],
        [0.        , 0.00901487, 0.        , ..., 0.00497372,
         0.00805673, 0.        ]]])
Coordinates:
  * roi      (roi) int64 0 1 2 3 4 5 6 7 ... 1487 1488 1489 1490 1491 1492 1493
  * frame    (frame) int64 0 1 2 3 4 5 6 7 8 ... 892 893 894 895 896 897 898 899
  * repeat   (repeat) int64 0 1 2 3 4 5 6 7 8 9 ... 21 22 23 24 25 26 27 28 29

In [11]:
nm._metrics = None
nm.metrics

mean_responses  pref_response  \
0     [0.001866733686377605, 0.001866733686377605, 0...       0.013769   
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...       0.017468   
2     [0.00013903708507617313, 0.0001390370850761731...       0.048952   
3     [0.0007588069187477231, 0.0007588069187477231,...         0.0066   
4     [0.002268267640223106, 0.0020592845821132263, ...       0.008462   
...                                                 ...            ...   
1489                                                NaN           <NA>   
1490                                                NaN           <NA>   
1491                                                NaN           <NA>   
1492                                                NaN           <NA>   
1493                                                NaN           <NA>   

      pref_img  pref_img_idx    z_score  \
0          722           722  10.604221   
1          796           796  66.321572   
2          549           549  54.606507   
3          156           156  24.005077   
4          785           785   31.22578   
...        ...           ...        ...   
1489      <NA>          <NA>       <NA>   
1490      <NA>          <NA>       <NA>   
1491      <NA>          <NA>       <NA>   
1492      <NA>          <NA>       <NA>   
1493      <NA>          <NA>       <NA>   

                                      z_score_responses  response_p  \
0     [0.3817734956745452, 0.3817734956745452, 0.091...         0.0   
1     [-1.4193242499141945, -1.4193242499141945, -1....         0.0   
2     [-0.9364568571321571, -0.9364568571321571, -0....         0.0   
3     [1.5826271029007597, 1.5826271029007597, 2.644...         0.0   
4     [7.2880641056720465, 6.480441095450999, 4.6183...         0.0   
...                                                 ...         ...   
1489                                                NaN        <NA>   
1490                                                NaN        <NA>   
1491                                                NaN        <NA>   
1492                                                NaN        <NA>   
1493                                                NaN        <NA>   

      frac_responsive_trials  lifetime_sparseness  is_valid  \
0                   0.433333             0.961662      True   
1                        0.9             0.927578      True   
2                   0.866667             0.942079      True   
3                        0.6             0.949109      True   
4                   0.233333             0.960978      True   
...                      ...                  ...       ...   
1489                    <NA>                 <NA>     False   
1490                    <NA>                 <NA>     False   
1491                    <NA>                 <NA>     False   
1492                    <NA>                 <NA>     False   
1493                    <NA>                 <NA>     False   

      null_dist_multi_mean  null_dist_multi_std  
0                 0.001422             0.001164  
1                 0.000366             0.000258  
2                 0.000962             0.000879  
3                 0.000347              0.00026  
4                 0.000382             0.000259  
...                    ...                  ...  
1489              0.000444             0.000361  
1490              0.001734             0.001128  
1491              0.000577             0.000438  
1492              0.001336             0.000866  
1493              0.000307             0.000244  

[1494 rows x 12 columns]

In [12]:
for col in ("pref_response", "pref_img", "pref_img_idx", "z_score", "frac_responsive_trials", "lifetime_sparseness", "chisq_response_p"):
    if col in nm.metrics.columns:
        print(nm.metrics[col].values.astype(float))

[0.01376918 0.01746813 0.04895202 ...        nan        nan        nan]
[722. 796. 549. ...  nan  nan  nan]
[722. 796. 549. ...  nan  nan  nan]
[10.60422097 66.32157231 54.60650671 ...         nan         nan
         nan]
[0.43333333 0.9        0.86666667 ...        nan        nan        nan]
[0.96166243 0.92757809 0.94207912 ...        nan        nan        nan]


In [20]:
nm.metrics["pref_img_idx"].fillna(-1).values.astype(int)

array([722, 796, 549, ...,  -1,  -1,  -1])

# Natural images

In [13]:
ni = NaturalImages(session, plane, ns_type="natural_images", compute_chisq=False)

In [14]:
ni.trial_responses

<xarray.DataArray 'trial_responses' (roi: 1494, image: 118, trial: 8)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.00779962,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00706757],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.0286109 ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00677058],
        ...,
        [0.        , 0.        , 0.        , ..., 0.01202319,
         0.00671483, 0.        ],
        [0.        , 0.        , 0.        , ..., 0.00715046,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]]])
Coordinates:
  * roi      (roi) int64 0 1 2 3 4 5 6 7 ... 1487 1488 1489 1490 1491 1492 1493
  * image    (image) int64 0 1 2 3 4 5 6 7 8 ... 110 111 112 113 114 115 116 117
  * trial    (trial) int64 0 1 2 3 4 5 6 7

In [15]:
ni._metrics = None
ni.metrics

mean_responses  pref_response  \
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.001...       0.021479   
1     [0.0008834462496452034, 0.0007721012807451189,...       0.003443   
2     [0.01385312236379832, 0.0, 0.00218314840458333...       0.013853   
3     [0.0009870454668998718, 0.0, 0.001305399229750...       0.004555   
4     [0.0, 0.002905067056417465, 0.0, 0.0, 0.0, 0.0...       0.011888   
...                                                 ...            ...   
1489                                                NaN           <NA>   
1490                                                NaN           <NA>   
1491                                                NaN           <NA>   
1492                                                NaN           <NA>   
1493                                                NaN           <NA>   

      pref_img  pref_img_idx    z_score  \
0           58            58   7.342219   
1           50            50   4.951302   
2            0             0   6.160712   
3           44            44   6.989823   
4           74            74  18.605673   
...        ...           ...        ...   
1489      <NA>          <NA>       <NA>   
1490      <NA>          <NA>       <NA>   
1491      <NA>          <NA>       <NA>   
1492      <NA>          <NA>       <NA>   
1493      <NA>          <NA>       <NA>   

                                      z_score_responses  response_p  \
0     [-0.5192827749593589, -0.5192827749593589, -0....      0.0008   
1     [0.8344111311440702, 0.6553441618385374, -0.58...      0.0029   
2     [6.1607124402444, -0.4734497520906591, 0.57204...      0.0026   
3     [1.06893687260134, -0.5688478077180369, 1.5971...      0.0001   
4     [-0.6108887914995118, 4.085201399747715, -0.61...         0.0   
...                                                 ...         ...   
1489                                                NaN        <NA>   
1490                                                NaN        <NA>   
1491                                                NaN        <NA>   
1492                                                NaN        <NA>   
1493                                                NaN        <NA>   

      frac_responsive_trials  lifetime_sparseness  is_valid  \
0                      0.375             0.968509      True   
1                        1.0             0.950836      True   
2                       0.25             0.970894      True   
3                        1.0             0.949431      True   
4                        1.0             0.966525      True   
...                      ...                  ...       ...   
1489                    <NA>                 <NA>     False   
1490                    <NA>                 <NA>     False   
1491                    <NA>                 <NA>     False   
1492                    <NA>                 <NA>     False   
1493                    <NA>                 <NA>     False   

      null_dist_multi_mean  null_dist_multi_std  
0                 0.001419             0.002732  
1                 0.000365             0.000622  
2                 0.000989             0.002088  
3                 0.000343             0.000603  
4                 0.000378             0.000619  
...                    ...                  ...  
1489              0.000464             0.000887  
1490              0.001743             0.002679  
1491              0.000558             0.001031  
1492              0.001394             0.002098  
1493               0.00031             0.000586  

[1494 rows x 12 columns]

# NI 12

In [13]:
ni12 = NaturalImages(session, plane, ns_type="natural_images_12", compute_chisq=False)

In [14]:
ni12.image_indices

array([ 2,  4,  5,  6,  9, 23, 27, 29, 32, 47, 62, 68])

In [15]:
ni12.trial_responses

<xarray.DataArray 'trial_responses' (roi: 1234, image: 12, trial: 40)>
array([[[0.02935483, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.0164012 , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00941985],
        ...,
        [0.        , 0.01162643, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.03633061, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.00888378,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.01887433, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.01048658, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00872612],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]]])
Coordinates:
  * roi      (roi) int64 0 1 2 3 4 5 6 7 ... 1227 1228 1229 1230 1231 1232 1233
  * image    (image) int64 2 4 5 6 9 23 27 29 32 47 62 68
  * trial    (trial) int64 0 1 2 3 4 5 6 7 8 9 ... 30 31 32 33 34 35 36 37 38 39