In [16]:
import numpy as np

from allen_v1dd.client import OPhysClient
from allen_v1dd.stimulus_analysis import NaturalImages, NaturalMovie

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
client = OPhysClient("/Users/chase/Desktop/test_v1dd_data/")

In [25]:
session = client.load_ophys_session("M438833_13")

In [26]:
plane = session.get_planes()[0]

In [27]:
nm = NaturalMovie(session, plane, compute_chisq=False)

In [28]:
nm.frame_indices

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [30]:
nm.stim_meta

{'num_samples': 27000}

In [29]:
for frame_i in nm.frame_indices:
    stim_idx = nm.get_stim_idx(frame_i)
    frame_data = nm.sweep_responses[stim_idx, :].T # shape (n_rois, n_frame_repeats) note n_frame_repeats not necessarily = n_repeats
    print(frame_data.shape)

    if frame_i > 10:
        break


(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)
(1494, 30)


In [23]:
nm.sweep_responses.shape

(29700, 1234)

In [7]:
nm.trial_responses

<xarray.DataArray 'trial_responses' (roi: 1234, frame: 3600, repeat: 9)>
array([[[0.        , 0.        , 0.        , ..., 0.00641277,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.00678488, ..., 0.        ,
         0.        ,        nan],
        [0.        , 0.        , 0.00678488, ..., 0.        ,
         0.        ,        nan],
        [0.        , 0.        , 0.00678488, ..., 0.        ,
         0.        ,        nan]],

       [[0.        , 0.01183315, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.01183315, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.01183315, 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        ,        nan],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        ,        nan],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        ,        nan]],

       [[0.00498817, 0.        , 0.        , ..., 0.        ,
         0.00738422, 0.        ],
        [0.00498817, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.00498817, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.00738422,
         0.        ,        nan],
        [0.        , 0.        , 0.        , ..., 0.00738422,
         0.        ,        nan],
        [0.        , 0.        , 0.        , ..., 0.00738422,
         0.        ,        nan]]])
Coordinates:
  * roi      (roi) int64 0 1 2 3 4 5 6 7 ... 1227 1228 1229 1230 1231 1232 1233
  * frame    (frame) int64 0 1 2 3 4 5 6 ... 3593 3594 3595 3596 3597 3598 3599
  * repeat   (repeat) int64 0 1 2 3 4 5 6 7 8

In [8]:
nm._metrics = None
nm.metrics

mean_responses  pref_response  \
0     [0.0024628344302376113, 0.000996428852279981, ...       0.104166   
1     [0.0013147943342725437, 0.0013147943342725437,...        0.11547   
2     [0.0028068099377883803, 0.00182124020324813, 0...       0.016202   
3     [0.0008491716968516508, 0.0008491716968516508,...       0.110897   
4     [0.0013966974284913805, 0.0021640430721971723,...       0.063971   
...                                                 ...            ...   
1229                                                NaN           <NA>   
1230                                                NaN           <NA>   
1231                                                NaN           <NA>   
1232                                                NaN           <NA>   
1233                                                NaN           <NA>   

      pref_img  pref_img_idx     z_score  \
0         3359          3359  198.028746   
1         3355          3355  168.181193   
2         2703          2703   13.812229   
3         1911          1911  108.424638   
4         1632          1632   53.855924   
...        ...           ...         ...   
1229      <NA>          <NA>        <NA>   
1230      <NA>          <NA>        <NA>   
1231      <NA>          <NA>        <NA>   
1232      <NA>          <NA>        <NA>   
1233      <NA>          <NA>        <NA>   

                                      z_score_responses  response_p  \
0     [3.8732633656211175, 1.0738479745690706, -0.82...         0.0   
1     [1.0924351779313988, 1.0924351779313988, 1.092...         0.0   
2     [1.6760915892267725, 0.7831682086870884, 1.419...         0.0   
3     [0.0474240563613821, 0.0474240563613821, 0.047...         0.0   
4     [0.42604816594383343, 1.0812515459070176, 1.08...         0.0   
...                                                 ...         ...   
1229                                                NaN        <NA>   
1230                                                NaN        <NA>   
1231                                                NaN        <NA>   
1232                                                NaN        <NA>   
1233                                                NaN        <NA>   

      frac_responsive_trials  lifetime_sparseness  is_valid  \
0                        1.0              0.95472      True   
1                        1.0             0.970111      True   
2                      0.625             0.929998      True   
3                        1.0             0.967538      True   
4                      0.875             0.944891      True   
...                      ...                  ...       ...   
1229                    <NA>                 <NA>     False   
1230                    <NA>                 <NA>     False   
1231                    <NA>                 <NA>     False   
1232                    <NA>                 <NA>     False   
1233                    <NA>                 <NA>     False   

      null_dist_multi_mean  null_dist_multi_std  
0                 0.000434             0.000524  
1                 0.000568             0.000683  
2                 0.000957             0.001104  
3                 0.000801             0.001015  
4                 0.000898             0.001171  
...                    ...                  ...  
1229              0.000503             0.000621  
1230              0.000358             0.000511  
1231               0.00038              0.00052  
1232              0.000854              0.00098  
1233              0.000468             0.000583  

[1234 rows x 12 columns]

In [9]:
for col in ("pref_response", "pref_img", "pref_img_idx", "z_score", "frac_responsive_trials", "lifetime_sparseness", "chisq_response_p"):
    if col in nm.metrics.columns:
        print(nm.metrics[col].values.astype(float))

[0.10416646 0.11546958 0.01620215 ...        nan        nan        nan]
[3359. 3355. 2703. ...   nan   nan   nan]
[3359. 3355. 2703. ...   nan   nan   nan]
[198.02874573 168.18119316  13.81222851 ...          nan          nan
          nan]
[1.    1.    0.625 ...   nan   nan   nan]
[0.95471996 0.97011059 0.92999817 ...        nan        nan        nan]


# Natural images

In [10]:
ni = NaturalImages(session, plane, ns_type="natural_images", compute_chisq=False)

In [11]:
ni.trial_responses

<xarray.DataArray 'trial_responses' (roi: 1234, image: 118, trial: 8)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.01157887, 0.00831025],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.02005187, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.01057072, 0.        , ..., 0.00852376,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.01787485, 0.00798861, ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00924465],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]]])
Coordinates:
  * roi      (roi) int64 0 1 2 3 4 5 6 7 ... 1227 1228 1229 1230 1231 1232 1233
  * image    (image) int64 0 1 2 3 4 5 6 7 8 ... 110 111 112 113 114 115 116 117
  * trial    (trial) int64 0 1 2 3 4 5 6 7

In [12]:
ni._metrics = None
ni.metrics

mean_responses  pref_response  \
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.002754260902293026...       0.005407   
1     [0.0, 0.0, 0.0, 0.0, 0.0011023185215890408, 0....       0.005805   
2     [0.0, 0.0, 0.0, 0.0, 0.0, 0.001122064655646681...       0.005466   
3     [0.0023044361732900143, 0.0022017365554347634,...       0.007322   
4     [0.0, 0.0010135923512279987, 0.0, 0.0010433017...       0.009385   
...                                                 ...            ...   
1229                                                NaN           <NA>   
1230                                                NaN           <NA>   
1231                                                NaN           <NA>   
1232                                                NaN           <NA>   
1233                                                NaN           <NA>   

      pref_img  pref_img_idx   z_score  \
0           85            85  7.256062   
1            8             8  5.727409   
2           88            88  3.174394   
3           60            60  5.213178   
4           69            69   5.62033   
...        ...           ...       ...   
1229      <NA>          <NA>      <NA>   
1230      <NA>          <NA>      <NA>   
1231      <NA>          <NA>      <NA>   
1232      <NA>          <NA>      <NA>   
1233      <NA>          <NA>      <NA>   

                                      z_score_responses  response_p  \
0     [-0.6180092431948642, -0.6180092431948642, -0....      0.0001   
1     [-0.634178776433733, -0.634178776433733, -0.63...      0.0004   
2     [-0.6720224362578373, -0.6720224362578373, -0....      0.0122   
3     [1.226503748186088, 1.144899658009741, -0.6045...      0.0015   
4     [-0.5780763610021126, 0.09137265714450787, -0....      0.0091   
...                                                 ...         ...   
1229                                                NaN        <NA>   
1230                                                NaN        <NA>   
1231                                                NaN        <NA>   
1232                                                NaN        <NA>   
1233                                                NaN        <NA>   

      frac_responsive_trials  lifetime_sparseness  is_valid  \
0                       0.25              0.93687      True   
1                        1.0             0.939181      True   
2                       0.25             0.950723      True   
3                        0.5             0.939267      True   
4                        0.5             0.943568      True   
...                      ...                  ...       ...   
1229                    <NA>                 <NA>     False   
1230                    <NA>                 <NA>     False   
1231                    <NA>                 <NA>     False   
1232                    <NA>                 <NA>     False   
1233                    <NA>                 <NA>     False   

      null_dist_multi_mean  null_dist_multi_std  
0                 0.000424             0.000687  
1                 0.000579             0.000912  
2                 0.000955             0.001421  
3                 0.000761             0.001259  
4                 0.000875             0.001514  
...                    ...                  ...  
1229              0.000509             0.000833  
1230               0.00036             0.000667  
1231              0.000366             0.000661  
1232              0.000824             0.001261  
1233               0.00047             0.000759  

[1234 rows x 12 columns]

# NI 12

In [13]:
ni12 = NaturalImages(session, plane, ns_type="natural_images_12", compute_chisq=False)

In [14]:
ni12.image_indices

array([ 2,  4,  5,  6,  9, 23, 27, 29, 32, 47, 62, 68])

In [15]:
ni12.trial_responses

<xarray.DataArray 'trial_responses' (roi: 1234, image: 12, trial: 40)>
array([[[0.02935483, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.0164012 , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00941985],
        ...,
        [0.        , 0.01162643, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.03633061, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.00888378,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.01887433, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.01048658, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00872612],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]]])
Coordinates:
  * roi      (roi) int64 0 1 2 3 4 5 6 7 ... 1227 1228 1229 1230 1231 1232 1233
  * image    (image) int64 2 4 5 6 9 23 27 29 32 47 62 68
  * trial    (trial) int64 0 1 2 3 4 5 6 7 8 9 ... 30 31 32 33 34 35 36 37 38 39