In [1]:
import numpy as np

from allen_v1dd.client import OPhysClient
from allen_v1dd.stimulus_analysis import NaturalImages, NaturalMovie

%load_ext autoreload
%autoreload 2

In [2]:
client = OPhysClient("/Users/chase/Desktop/test_v1dd_data/")

In [3]:
session = client.load_ophys_session("M409828_13")

In [4]:
plane = session.get_planes()[0]

In [5]:
nm = NaturalMovie(session, plane, compute_chisq=False)

In [7]:
nm.frame_indices

array([   0,    1,    2, ..., 3597, 3598, 3599])

In [8]:
nm.trial_responses

<xarray.DataArray 'trial_responses' (roi: 1234, frame: 3600, repeat: 9)>
array([[[0.        , 0.        , 0.        , ..., 0.00641277,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.00678488, ..., 0.        ,
         0.        ,        nan],
        [0.        , 0.        , 0.00678488, ..., 0.        ,
         0.        ,        nan],
        [0.        , 0.        , 0.00678488, ..., 0.        ,
         0.        ,        nan]],

       [[0.        , 0.01183315, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.01183315, 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.01183315, 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        ,        nan],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        ,        nan],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        ,        nan]],

       [[0.00498817, 0.        , 0.        , ..., 0.        ,
         0.00738422, 0.        ],
        [0.00498817, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.00498817, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.00738422,
         0.        ,        nan],
        [0.        , 0.        , 0.        , ..., 0.00738422,
         0.        ,        nan],
        [0.        , 0.        , 0.        , ..., 0.00738422,
         0.        ,        nan]]])
Coordinates:
  * roi      (roi) int64 0 1 2 3 4 5 6 7 ... 1227 1228 1229 1230 1231 1232 1233
  * frame    (frame) int64 0 1 2 3 4 5 6 ... 3593 3594 3595 3596 3597 3598 3599
  * repeat   (repeat) int64 0 1 2 3 4 5 6 7 8

In [9]:
nm._metrics = None
nm.metrics

mean_responses  pref_response  \
0     [0.0024628344302376113, 0.000996428852279981, ...       0.104166   
1     [0.0013147943342725437, 0.0013147943342725437,...        0.11547   
2     [0.0028068099377883803, 0.00182124020324813, 0...       0.016202   
3     [0.0008491716968516508, 0.0008491716968516508,...       0.110897   
4     [0.0013966974284913805, 0.0021640430721971723,...       0.063971   
...                                                 ...            ...   
1229                                                NaN           <NA>   
1230                                                NaN           <NA>   
1231                                                NaN           <NA>   
1232                                                NaN           <NA>   
1233                                                NaN           <NA>   

      pref_img  pref_img_idx     z_score  \
0         3359          3359    201.4925   
1         3355          3355   168.12168   
2         2703          2703   13.667308   
3         1911          1911  111.172483   
4         1632          1632   53.568062   
...        ...           ...         ...   
1229      <NA>          <NA>        <NA>   
1230      <NA>          <NA>        <NA>   
1231      <NA>          <NA>        <NA>   
1232      <NA>          <NA>        <NA>   
1233      <NA>          <NA>        <NA>   

                                      z_score_responses  response_p  \
0     [3.961822672449048, 1.1137423019688077, -0.821...         0.0   
1     [1.098484253153204, 1.098484253153204, 1.09848...         0.0   
2     [1.6539487851930406, 0.7700588497385873, 1.400...         0.0   
3     [0.06589445119463842, 0.06589445119463842, 0.0...         0.0   
4     [0.4240718012792317, 1.0757694018800625, 1.075...         0.0   
...                                                 ...         ...   
1229                                                NaN        <NA>   
1230                                                NaN        <NA>   
1231                                                NaN        <NA>   
1232                                                NaN        <NA>   
1233                                                NaN        <NA>   

      frac_responsive_trials  lifetime_sparseness  is_valid  \
0                        1.0              0.95472      True   
1                        1.0             0.970111      True   
2                      0.625             0.929998      True   
3                        1.0             0.967538      True   
4                      0.875             0.944891      True   
...                      ...                  ...       ...   
1229                    <NA>                 <NA>     False   
1230                    <NA>                 <NA>     False   
1231                    <NA>                 <NA>     False   
1232                    <NA>                 <NA>     False   
1233                    <NA>                 <NA>     False   

      null_dist_multi_mean  null_dist_multi_std  
0                 0.000423             0.000515  
1                 0.000564             0.000683  
2                 0.000963             0.001115  
3                 0.000784              0.00099  
4                 0.000897             0.001177  
...                    ...                  ...  
1229              0.000499             0.000621  
1230              0.000359              0.00051  
1231              0.000372             0.000511  
1232              0.000836             0.000977  
1233              0.000472             0.000585  

[1234 rows x 12 columns]

In [10]:
for col in ("pref_response", "pref_img", "pref_img_idx", "z_score", "frac_responsive_trials", "lifetime_sparseness", "chisq_response_p"):
    if col in nm.metrics.columns:
        print(nm.metrics[col].values.astype(float))

[0.10416646 0.11546958 0.01620215 ...        nan        nan        nan]
[3359. 3355. 2703. ...   nan   nan   nan]
[3359. 3355. 2703. ...   nan   nan   nan]
[201.49249994 168.12167979  13.66730795 ...          nan          nan
          nan]
[1.    1.    0.625 ...   nan   nan   nan]
[0.95471996 0.97011059 0.92999817 ...        nan        nan        nan]


# Natural images

In [11]:
ni = NaturalImages(session, plane, ns_type="natural_images", compute_chisq=False)

In [12]:
ni.trial_responses

<xarray.DataArray 'trial_responses' (roi: 1234, image: 118, trial: 8)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.01157887, 0.00831025],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.02005187, 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.01057072, 0.        , ..., 0.00852376,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.01787485, 0.00798861, ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.00924465],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]]])
Coordinates:
  * roi      (roi) int64 0 1 2 3 4 5 6 7 ... 1227 1228 1229 1230 1231 1232 1233
  * image    (image) int64 0 1 2 3 4 5 6 7 8 ... 110 111 112 113 114 115 116 117
  * trial    (trial) int64 0 1 2 3 4 5 6 7

In [13]:
ni._metrics = None
ni.metrics

mean_responses  pref_response  \
0     [0.0, 0.0, 0.0, 0.0, 0.0, 0.002754260902293026...       0.005407   
1     [0.0, 0.0, 0.0, 0.0, 0.0011023185215890408, 0....       0.005805   
2     [0.0, 0.0, 0.0, 0.0, 0.0, 0.001122064655646681...       0.005466   
3     [0.0023044361732900143, 0.0022017365554347634,...       0.007322   
4     [0.0, 0.0010135923512279987, 0.0, 0.0010433017...       0.009385   
...                                                 ...            ...   
1229                                                NaN           <NA>   
1230                                                NaN           <NA>   
1231                                                NaN           <NA>   
1232                                                NaN           <NA>   
1233                                                NaN           <NA>   

      pref_img  pref_img_idx   z_score  \
0           85            85   7.27809   
1            8             8  5.791055   
2           88            88  3.132349   
3           60            60  5.249866   
4           69            69  5.483555   
...        ...           ...       ...   
1229      <NA>          <NA>      <NA>   
1230      <NA>          <NA>      <NA>   
1231      <NA>          <NA>      <NA>   
1232      <NA>          <NA>      <NA>   
1233      <NA>          <NA>      <NA>   

                                      z_score_responses  response_p  \
0     [-0.6156171469533073, -0.6156171469533073, -0....         0.0   
1     [-0.6422093251883674, -0.6422093251883674, -0....         0.0   
2     [-0.6647365660840353, -0.6647365660840353, -0....       0.014   
3     [1.2320266478719986, 1.1497846330661494, -0.61...      0.0016   
4     [-0.572881981177021, 0.0812337661878783, -0.57...      0.0097   
...                                                 ...         ...   
1229                                                NaN        <NA>   
1230                                                NaN        <NA>   
1231                                                NaN        <NA>   
1232                                                NaN        <NA>   
1233                                                NaN        <NA>   

      frac_responsive_trials  lifetime_sparseness  is_valid  \
0                       0.25              0.93687      True   
1                      0.375             0.939181      True   
2                       0.25             0.950723      True   
3                        0.5             0.939267      True   
4                        0.5             0.943568      True   
...                      ...                  ...       ...   
1229                    <NA>                 <NA>     False   
1230                    <NA>                 <NA>     False   
1231                    <NA>                 <NA>     False   
1232                    <NA>                 <NA>     False   
1233                    <NA>                 <NA>     False   

      null_dist_multi_mean  null_dist_multi_std  
0                 0.000422             0.000685  
1                 0.000579             0.000902  
2                 0.000957              0.00144  
3                 0.000766             0.001249  
4                 0.000888              0.00155  
...                    ...                  ...  
1229              0.000509             0.000813  
1230              0.000368             0.000677  
1231              0.000379             0.000688  
1232              0.000829             0.001291  
1233              0.000476             0.000781  

[1234 rows x 12 columns]